[package]
name = "patina"
version = "0.1.0"
edition = "2021"
description = "a simple static blog generator"

[dependencies]
chrono = "0.4"
clap = { version = "3.0.10", features = ["derive"] }
handlebars = "4.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.23"
strum_macros = "0.23"
