[package]
name = "patina"
version = "0.1.0"
edition = "2021"
description = "a simple static blog generator"

[dependencies]
chrono = "0.4"
clap = { version = "4.1", features = ["derive"] }
futures = "0.3"
handlebars = "4.3"
inquire = "0.6"
pulldown-cmark = { version = "0.9", default-features = false }
regex = "1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.24"
strum_macros = "0.24"
tokio = { version = "1", features = ["full"] }
